# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GBm1czpOhNgtyEQ3RPlfcRrSgwm77lzR
"""

# Reto 1: Simular la tortuga usando solo texto, print() e input()

def mover_derecha(pasos):
    """Imprime una flecha hacia la derecha según pasos."""
    print("-" * pasos + ">")

def mover_izquierda(pasos):
    """Imprime una flecha hacia la izquierda según pasos."""
    print("<" + "-" * pasos)

def mover_arriba(pasos):
    """Imprime un movimiento hacia arriba en vertical."""
    for _ in range(pasos):
        print("^")

def mover_abajo(pasos):
    """Imprime un movimiento hacia abajo en vertical."""
    for _ in range(pasos):
        print("v")

# --- Programa principal ---
print("Simulador de movimientos de la tortuga (versión texto)")
print("Opciones: derecha, izquierda, arriba, abajo")

direccion = input("¿Hacia dónde quieres mover la tortuga? ").strip().lower()
pasos = int(input("¿Cuántos pasos quieres mover? "))

print("\nResultado del movimiento:\n")

if direccion == "derecha":
    mover_derecha(pasos)
elif direccion == "izquierda":
    mover_izquierda(pasos)
elif direccion == "arriba":
    mover_arriba(pasos)
elif direccion == "abajo":
    mover_abajo(pasos)
    print("Dirección no válida. Intenta con: derecha, izquierda, arriba o abajo.")
  # Reto 2: Tortuga bajando con solo print() e input()

print("Simulador: Tortuga moviéndose hacia abajo")

# Pedimos cuántos pasos debe bajar
pasos = int(input("¿Cuántos pasos quieres que la tortuga baje? "))

print("\nRastro generado:\n")

# Imprime una línea vertical hacia abajo
for _ in range(pasos):
    print("|")

print("v")  # Flecha final indicando la dirección hacia abajo

# Reto 3: Girar y dibujar usando solo print() e input()
# Dibujar una "L" como en la versión gráfica de turtle

print("Simulación de una tortuga que avanza y luego gira hacia abajo\n")

# Pedimos los valores al usuario
horizontal = int(input("¿Cuántos pasos debe avanzar hacia la derecha? "))
vertical = int(input("¿Cuántos pasos debe avanzar hacia abajo? "))

print("\nDibujo generado:\n")

# --- Tramo horizontal ---
print("-" * horizontal + ">")

# --- Tramo vertical ---
# El primer segmento vertical empieza alineado al final del horizontal
for _ in range(vertical - 1):
    print(" " * horizontal + "|")

# Flecha final hacia abajo
print(" " * horizontal + "v")

# Reto 4: Encapsula los comportamientos usando funciones

# Variable global para recordar cuántos pasos horizontales se han dibujado.
posicion_horizontal = 0

def adelante(n):
    """Dibuja el movimiento hacia la derecha usando '-' y '>'."""
    global posicion_horizontal
    print("-" * n + ">")
    posicion_horizontal += n

def abajo(n):
    """Dibuja el movimiento hacia abajo usando '|' y 'v'."""
    global posicion_horizontal
    # Líneas verticales
    for _ in range(n - 1):
        print(" " * posicion_horizontal + "|")
    # Flecha final
    print(" " * posicion_horizontal + "v")

    # Variable global para recordar la posición horizontal actual
pos_x = 0

def adelante(n):
    """
    Dibuja un tramo horizontal hacia la derecha.
    Conserva la posición horizontal acumulada.
    """
    global pos_x
    # Imprime espacios hasta la posición actual y luego la flecha
    print(" " * pos_x + "-" * n + ">")
    # Actualiza la posición: avanzamos n pasos
    pos_x += n

def abajo(n):
    """
    Dibuja un tramo vertical hacia abajo.
    Usa la posición horizontal acumulada (pos_x)
    para alinear correctamente el tramo.
    """
    global pos_x
    # n-1 líneas con '|'
    for _ in range(n - 1):
        print(" " * pos_x + "|")
    # Línea final con 'v'
    print(" " * pos_x + "v")


# --------------------------
# Ejemplo: la tortuga baja 3 escalones
# Cada escalón conserva la posición horizontal acumulada
# --------------------------

# Escalón 1
adelante(5)
abajo(2)

# Escalón 2
adelante(5)
abajo(2)

# Escalón 3
adelante(5)
abajo(2)